testing simultaneous array calclation

In [5]:
import numpy as np
p = np.zeros((5,5))
print(p)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [6]:
print(p.shape)

(5, 5)


In [7]:
matrix =[i for i in range(0,10)]
print(matrix)##???

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
for i in range(0,5):
    for j in range(0,5):
        p[i][j] = 5*i+j
print(p)

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]


In [9]:
print(p*p)

[[   0.    1.    4.    9.   16.]
 [  25.   36.   49.   64.   81.]
 [ 100.  121.  144.  169.  196.]
 [ 225.  256.  289.  324.  361.]
 [ 400.  441.  484.  529.  576.]]


In [10]:
print(np.dot(p,p))

[[  150.   160.   170.   180.   190.]
 [  400.   435.   470.   505.   540.]
 [  650.   710.   770.   830.   890.]
 [  900.   985.  1070.  1155.  1240.]
 [ 1150.  1260.  1370.  1480.  1590.]]


In [11]:
no_zero = p + 1
print(no_zero)

[[  1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.]]


In [12]:
test_exp = np.exp(p)
print(test_exp)

[[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
    5.45981500e+01]
 [  1.48413159e+02   4.03428793e+02   1.09663316e+03   2.98095799e+03
    8.10308393e+03]
 [  2.20264658e+04   5.98741417e+04   1.62754791e+05   4.42413392e+05
    1.20260428e+06]
 [  3.26901737e+06   8.88611052e+06   2.41549528e+07   6.56599691e+07
    1.78482301e+08]
 [  4.85165195e+08   1.31881573e+09   3.58491285e+09   9.74480345e+09
    2.64891221e+10]]


In [13]:
sigmoid = (1/(1+np.exp(-p)))
print(sigmoid)

[[ 0.5         0.73105858  0.88079708  0.95257413  0.98201379]
 [ 0.99330715  0.99752738  0.99908895  0.99966465  0.99987661]
 [ 0.9999546   0.9999833   0.99999386  0.99999774  0.99999917]
 [ 0.99999969  0.99999989  0.99999996  0.99999998  0.99999999]
 [ 1.          1.          1.          1.          1.        ]]


test complete


In [15]:
print(sum(no_zero))

[ 55.  60.  65.  70.  75.]
